project:
  type: website

website:
  title: "Learn R: As a Language"
  site-url: https://www.learnr-book.info/
  description: "Web site supporting the book Learn R: As a Language by Pedro J. Aphalo."
  favicon: r4p-favicon.png
  search: true
  navbar:
    left:
      - text: "Book"
        icon: book
        menu:
        - text: "Contents (2ed)"
          icon: list-columns
          href: contents-2ed.qmd
        - text: "Preface (2ed)"
          icon: book
          href: preface-2ed.qmd
        - text: "Contents (1ed)"
          icon: list-columns
          href: contents-1ed.qmd
        - text: "Preface (1ed)"
          icon: book
          href: preface-1ed.qmd
      - text: "R code"
        icon: paperclip
        menu:
        - text: "'learnrbook' package"
          icon: box-seam
          href: https://docs.r4photobiology.info/learnrbook/
        - text: "Wordcloud (cover)"
          icon: file
          href: wordcloud.html
      - text: "Also by the author"
        icon: folder2-open
        menu:
        - text: "Web pages on R"
          icon: file-richtext
          href: https://www.r4photobiology.info/r-index.html
        - text: "Packages (HTML documentation)"
          icon: journals
          href: https://docs.r4photobiology.info/
        - text: "Packages (at R-Universe)"
          icon: rocket-takeoff
          href: https://aphalo.r-universe.dev/
      - text: "About"
        icon: person
        href: about.html
      - text: "GitHub"
        icon: github
        href: https://github.com/aphalo/learnr-book-crc
  page-footer:
    right:
      - text: "&copy; 2015-2024 Pedro J. Aphalo"
        href: about.qmd
    center:
      - text: "Learn R: As a Language"
    left:
      - text: "P. J. Aphalo @ ORCID"
        href: https://orcid.org/0000-0003-3385-972X
format:
  html:
    theme: spacelab
    linkcolor: "#0000A0"
    css: styles.css
    highlight-style: github
    date-format: iso
    toc: true

number-sections: true
number-depth: 3

editor: source
license: "CC BY-SA"

# for supported icons see https://icons.getbootstrap.com/
# for themes
